# 搭建神经网络进行回归

## 导入模块

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

## 基于keras构建网络模型

In [ ]:
model = tf.keras.Sequential()
model.add(layers.Dense(16))
model.add(layers.Dense(32))
model.add(layers.Dense(1))

In [ ]:
# 网络配置
model.compile(optimizer = tf.keras.optimizers.SGD(0.001),loss='mean_squared_error')

In [ ]:
model.fit(input_feature,labels,validation_split=0.25,epoch=10,batch_size=64)

In [ ]:
# 模型每层的参数信息
model.summary()

In [ ]:
predict_label = model.predict(input_features)

# 搭建神经网络进行分类

## 导入模块

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

## mnist数据集

In [ ]:
import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

# X:mnist.test.images,y:mnist.test.labels

In [ ]:
x_train = mnist.train.images
x_test = mnist.test.images
y_train = mnist.train.labels
y_test = mnist.test.labels

In [ ]:
plt.imshow(x_train[0].reshape((28,28)),cmap='gray')
print(x_train.shape)

In [ ]:
print(y_train[0])

## 构建模型

In [ ]:
model = tf.keras.Sequential()
# 如果数据是个三维图片,有一个数据拉长处理
# model.add(layers.Flatten(input_shape=(28,28)))
model.add(layers.Dense(32,activation='relu'))
model.add(layers.Dense(32,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))

In [ ]:
# label是one-hot形式
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.CategoricalCrossentropy(),
             metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [ ]:
# label是index
# model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
#              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
#              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

In [ ]:
model.fit(x_train,y_train,epochs=5,batch_size=64,validation_data=(x_test,y_test))
# 860个batch？

# 或者
# model.fit(x_train,y_train,epochs=10)

In [ ]:
y_predict = model.predict(x_test)
for i in range(10):
    m = tf.keras.metrics.categorical_accuracy(y_test[i], y_predict[i])
    print('categorical_accuracy:',m.numpy())
    print('实际标签为：',y_train[i],' 预测标签为：',y_predict[i])    

## 模型评估

In [ ]:
test_loss,test_acc = model.evaluate(x_test,y_test,verbose=2)

## 模型保存

In [ ]:
model.save('model.h5')

# model.to_json() 
# model.get_weights()

## 导入模型

In [ ]:
model = keras.models.load_model('model.h5')

# tf.data模块常用函数

In [2]:
import numpy as np
import tensorflow as tf

input_data = np.arange(16)
dataset = tf.data.Dataset.from_tensor_slices(input_data)
for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


## repeat操作

In [3]:
dataset = tf.data.Dataset.from_tensor_slices(input_data)
dataset = dataset.repeat(2)
for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(11, shape=(

## batch操作

In [4]:
dataset = tf.data.Dataset.from_tensor_slices(input_data)
dataset = dataset.repeat(2).batch(4)
for data in dataset:
    print(data)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int32)


## shuffle操作

In [5]:
dataset = tf.data.Dataset.from_tensor_slices(input_data).shuffle(buffer_size=10).batch(4)
# shuffle：构建一个buffer_size大小的缓存区，在缓存区进行随机采样
for data in dataset:
    print(data)

tf.Tensor([2 5 1 7], shape=(4,), dtype=int32)
tf.Tensor([ 8  4 15  3], shape=(4,), dtype=int32)
tf.Tensor([11  0  6 12], shape=(4,), dtype=int32)
tf.Tensor([10 14 13  9], shape=(4,), dtype=int32)


## 重新训练 

In [ ]:
train = tf.data.Dataset.from_tensor_slices(x_train,y_train)
train = train.batch(32)
train = train.repeat()

valid = tf.data.Dataset.from_tensor_slices(x_test,y_test)
valid = train.batch(32)
valid = train.repeat()

model.fit(train,epochs=5,steps_per_epoch=100,validation_data=valid,validation_steps=100)