# tensorflow安装

1、安装anaconda，百度搜索

2、安装tensorflow

pip install -i https://pypi.doubanio.com/simple/ tensorflow

# tensorflow基础操作

> [tensorflow官网教程](https://tensorflow.google.cn/tutorials)

In [15]:
import tensorflow as tf
import numpy as np

In [16]:
tf.__version__

'2.5.0'

> 动态图(可以直接执行出结果)

## 变量及运算

In [17]:
x = [[1.]]
m = tf.matmul(x,x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [18]:
x = tf.constant([[1,9],[3,6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]])>

In [19]:
x = tf.add(x,1)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 4,  7]])>

## tensor是什么

> tensor即张量，数据处理计算单元，既可以是向量，也可以是矩阵，还可以是三维甚至四维的，可在gpu中进行加速。

## 转换格式

In [20]:
x.numpy()

array([[ 2, 10],
       [ 4,  7]])

In [21]:
x = tf.cast(x,tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2., 10.],
       [ 4.,  7.]], dtype=float32)>

In [22]:
x1 = np.ones([2,2]) 
x2 = tf.multiply(x1,2)  # 点乘
x2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 2.],
       [2., 2.]])>